#!/usr/bin/env ruby
require 'selenium-webdriver'
require 'thor'


class TestRunnerCLI < Thor
  default_task :start
  desc "start", "Run test suite"
  option :host, :required => true
  option :user, :required => true
  option :key, :required => true
  option :browser, :default => 'chrome'
  option :version, :default => '60'
  option :container, :default => true
  option :video, :type => :boolean, :default => true
  option :screenshot, :type => :boolean, :default => true
  
  def start()
    caps = {
      browserName: options[:browser],
      seleniumVersion: '3.4.0',
      _containerizedChef: options[:container],
      recordVideo: options[:video],
      recordScreenshots: options[:screenshot]
    }

    wd_url="http://#{options[:user]}:#{options[:key]}@#{options[:host]}:4444/wd/hub"
    base_url='https://www.saucelabs.com'
    puts "starting browser for cap #{caps.to_json}"
    driver = Selenium::WebDriver.for(:remote, url: wd_url, desired_capabilities: caps)
    driver.manage.timeouts.implicit_wait = 10
    driver.get("#{base_url}/test-guinea-pig.html")
    to_type = '0 1 2 3 4 5 6 7 8 9 '\
              'a b c d e f g h j k l m n o p q r s t u v w x y z'
    textarea = driver.find_element(:id, 'comments')
    textarea.send_keys(to_type)
    puts "Test completed"
    driver.quit()
  end
end

TestRunnerCLI.start(ARGV)